### ISSUE TITLE
Product Functions - After Registering

### ISSUE THREAD

**Issue by ptoulino** [Project-PICK/Project-PICK#10]
| 💈Task: | ⚙️Description: |
| ------:| -----------:|
| After registering | The username and password will be activated for login purposes |

***
<img width="400" alt="Screen Shot 2020-09-24 at 10 16 32 PM" src="https://user-images.githubusercontent.com/68033681/94229154-9d4ea700-feb3-11ea-8f39-c198be2d25d9.png">

***

**Comment by itravers** [comment]
This doesn't even make sense to me?

**Comment by itravers** [comment]
We don't need this, because issue #9 covers everything we'd do here.
