### ISSUE TITLE
Product Functions - Login

### ISSUE THREAD

**Issue by ptoulino** [Project-PICK/Project-PICK#11]
| 💈Task: | ⚙️Description: |
| ------:| -----------:|
| Log-in    | A registered user has to enter his/her unique user name/password combination in order to access the application |

***
<img width="400" alt="Screen Shot 2020-09-24 at 10 16 32 PM" src="https://user-images.githubusercontent.com/68033681/94229154-9d4ea700-feb3-11ea-8f39-c198be2d25d9.png">

***

**Comment by itravers** [comment]
Login and Registration are confirmed working as of commit 
8ed39a7
