### ISSUE TITLE
Product Functions - Demonstration

### ISSUE THREAD

**Issue by ptoulino** [Project-PICK/Project-PICK#12]
| 💈Task: | ⚙️Description: |
| ------:| -----------:|
| Demonstration   | An option available to the registered users allowing them to familiarize with the features of the application; the tutorial session will provide for a mock session to be performed by the user (without the score being stored in the record). Pop-up messages will help the user familiarize with the program |

***
<img width="400" alt="Screen Shot 2020-09-24 at 10 16 32 PM" src="https://user-images.githubusercontent.com/68033681/94229154-9d4ea700-feb3-11ea-8f39-c198be2d25d9.png">

***

**Comment by itravers** [comment]
Can someone look up how to do an attractive popup on a form in winforms?
