### ISSUE TITLE
Product Functions - User Logout,Exit,Settings

### ISSUE THREAD

**Issue by ptoulino** [Project-PICK/Project-PICK#14]
| 💈Task: | ⚙️Description: |
| ------:| -----------:|
| Log-out   | Users are able to log out in order to let another user to register or log-in |
|  Exit  | Users are able to exit the program |
| Settings  | An option allowing the user to modify the settings for the video learning session such as the level of difficulty and the video category, volume of the video and keyboard settings |

***
<img width="400" alt="Screen Shot 2020-09-24 at 10 16 32 PM" src="https://user-images.githubusercontent.com/68033681/94229154-9d4ea700-feb3-11ea-8f39-c198be2d25d9.png">

***

**Comment by itravers** [comment]
Please break this into 3 different issues, one for user logout, one for exiting, and one for adjusting settings.
Close this issue when those are created.
