### ISSUE TITLE
Data Schema

### ISSUE THREAD

**Issue by ptoulino** [Project-PICK/Project-PICK#16]
| 💈Task: | ⚙️Description: |
| ------:| -----------:|
| Create a DB documentation   | Developers should be able to reference this documentation and continuously update |

***
<img width="400" alt="Screen Shot 2020-09-24 at 10 16 32 PM" src="https://user-images.githubusercontent.com/68033681/94229154-9d4ea700-feb3-11ea-8f39-c198be2d25d9.png">

***

**Comment by itravers** [comment]
Looks like we came up with a better data schemea today.
