### ISSUE TITLE
Product Functions - Function that load pictures into Winforms 'box'

### ISSUE THREAD

**Issue by ptoulino** [Project-PICK/Project-PICK#18]
| 💈Task: | ⚙️Description: |
| ------:| -----------:|
| Loading pictures   | Create a function that loads picture from our dataset files into a Winforms box |

_Future editions will include loading **folders** into boxes_

**Comment by itravers** [comment]
This is exactly what I needed, we'll move this into a "test" folder, and then I'll be able to refer to it when we are loading pictures.
