### ISSUE TITLE
Product Enhancements- Scroll Box for Learning Section

### ISSUE THREAD

**Issue by ptoulino** [Project-PICK/Project-PICK#23]
| 💈Task: | ⚙️Description: |
| ------:| -----------:|
| Scroll Feature| Design a scroll theme for the learning section categories. |

**Comment by itravers** [comment]
Can you flush out what we mean by a scroll theme better? Do you just mean design a scroll-able gui?

**Comment by itravers** [comment]
This was finished with commmit 
fdbb4ad
