### ISSUE TITLE
POTENTIAL--Link potential site for ethics training videos/course & ADA

### ISSUE THREAD

**Issue by ptoulino** [Project-PICK/Project-PICK#35]
Links provided by @moorcan :

http://localethics.fppc.ca.gov/default.aspx

https://www.adabasics.org/

| 💈Task: | ⚙️Description: |
| ------:| -----------:|
| Potential link to ethics/ADA website  | Allow the user the click on 'ethics' module and be redirected to this page|

_**Potential issue:**_ Recording user progress upon completion/recording progress to 'score dashbord'

**Comment by itravers** [comment]
This doesn't make any sense.

I think candace was just posting links of training apps, not links we are supposed to actually link to.....
