### ISSUE TITLE
Go Back Button BUG

### ISSUE THREAD

**Issue by itravers** [Project-PICK/Project-PICK#51]
The go back button has ambiguous behavior, it does not always behave correctly. It has something to do with the state transition between forms. 

To recreate BUG:

RUN#1:
1. Set project up to boot to splash page.
2. Allow project to go to Login Page.
3. Press "Go Back" button. You will see that you are now on the splash screen again.

RUN#2:
1. Set Project up to boot to splash page
2. Allow project to go to login page.
3. Login.
4. Choose Artists and thier painting training.
5. click back button, you are taken to the choose trainer page.
6. Click back button, you are taken to the login page.
7. click back button, now the application asks if you want to exit, instead of showing the splash page again.

I believe this is at the root of the problem of not being able to boot to any page for debugging.

**Comment by ptoulino** [comment]
Completed by Kyle and Philip. Line 169 was commented out
