### ISSUE TITLE
Product Functions - Register

### ISSUE THREAD

**Issue by ptoulino** [Project-PICK/Project-PICK#9]
## Product Functions (last u pdated:9/23/20)
| 💈Task: | ⚙️Description : |
| ------:| -----------:|
| Register   | Users must register once in order to get access to the application |

***
<img width="400" alt="Screen Shot 2020-09-24 at 10 16 32 PM" src="https://user-images.githubusercontent.com/68033681/94229154-9d4ea700-feb3-11ea-8f39-c198be2d25d9.png">

***

**Comment by ptoulino** [comment]
❗️Pull Request #24 Needs _review_ and to be _enhanced_ into our login **LoginPage.cs**

❗️ We need to reference SQLite in our reference package, I only see Mono.Data.Sqlite on my end(on a mac this weekend and don't have aces to the pc)

**Comment by itravers** [comment]
I think issue #10 is unneeded if we have this, I'm closing that issue.

**Comment by itravers** [comment]
Registration is working as of commit 
8ed39a7
